# Generated by Django 2.0.2 on 2018-06-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_add',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='data_add',
            new_name='date_added',
        ),
    ]
